### ISSUE TITLE
Obtain Power from PM100 in Watts

### ISSUE THREAD

**Issue by jakestephen1** [clade/ThorlabsPM100#11]
Hi Pierre,

When I read values from the PM100 in Python, it gives the value in units of volts. How do I get it to read in units of watts?

**Comment by clade** [comment]
Are you talking about the older PM100 or the PM100A. The set of instruction is apparently not compatible between both devices, and th driver is made for the later. With the PM100, you should be able to access the power with inst.ask('POWER?') (or inst.query).
