### ISSUE TITLE
Running example: ValueError: 'term_chars' is not a valid attribute for type USBInstrument

### ISSUE THREAD

**Issue by KH-W27** [clade/ThorlabsPM100#12]
Running example script after installation. Fairly new to pyvisa, so not sure what the issue is here. Also when I search resource manager, no objects are returned but instrument is findable otherwise.

**Comment by clade** [comment]
Could you try without the term_char argument ?

**Comment by KH-W27** [comment]
Thanks for the quick reply! I get a different error "VisaIOError: VI_ERROR_RSRC_NFOUND (-1073807343): Insufficient location information or the requested device or resource is not present in the system." If I ask resource manager to list resources, it doesn't find it and returns empty brackets. If I use "import usbtmc usbtmc.list_devices()" I can find a location for it though, but I can't use this as a solution as I am unsure how to implement the 'you nedd to have read and write access to the ‘/dev/usbtmc0’' requirement. When I try that example I get the predictable "FileNotFoundError: [Errno 2] No such file or directory: '/dev/usbtmc0'". Apologies, I am fairly unfamiliar to this so it's probably clear to anyone who is not me!

**Comment by KH-W27** [comment]
My own stupid mistake sorry, I hadn't installed the NIVisa library on this machine. Thanks for your help! All working.
