### ISSUE TITLE
Only works on Linux? 

### ISSUE THREAD

**Issue by devmnob** [clade/ThorlabsPM100#16]
Only works on Linux? 
How can I get the connect string? USB0::0x0000::0x0000::xxxxxxxxx::INSTR

**Comment by clade** [comment]
With visa:

```
rm = visa.ResourceManager()
rm.list_resources()
```

**Comment by chemyibinjiang** [comment]
can this package be used for windows?

**Comment by clade** [comment]
On windows, you need to install visa, and it should work.

**Comment by chemyibinjiang** [comment]
it works well on windows using visa
