### ISSUE TITLE
Ask is deprecated in pyvisa

### ISSUE THREAD

**Issue by MarceloSemO** [clade/ThorlabsPM100#6]
When using the module I get the following warning from pyvisa's resources/messagebased.py file: 
```
FutureWarning: ask is deprecated and will be removed in 1.10, use query instead.
  '1.10, use query instead.', FutureWarning)
```
It would be nice if this module could be adapted accordingly.

**Comment by bleykauf** [comment]
Looks like this has already been done in https://github.com/clade/ThorlabsPM100/commit/ff9a9ebcf5caf2d585ddadfc5dcbe8ba31e3ac5b but not been pushed to PyPi.

**Comment by itayperl** [comment]
+1 for updating PyPI. The ask method does not exist anymore in the latest PyVISA master branch, so when they make a release ThorlabsPM100 will break.

**Comment by clade** [comment]
Pypi is now updated (version 1.2.1)
