### ISSUE TITLE
Switch console to local mode

### ISSUE THREAD

**Issue by ilyaradko** [clade/ThorlabsPM100#7]
Hello,

Is there a way to switch the PM100A/D console to a local mode (i.e., opposite to remote) after measurements are done? In Thorlabs' C++ API, there is a function `PM100D_close()` that does exactly this, but I could not find how to do the same using this Python package.

I tried releasing the ResourceManager like this:

```
rm = visa.ResourceManager()
inst = rm.open_resource('USB0::0x1313::0x8079::xxxxxxxx::INSTR')
power_meter = ThorlabsPM100(inst=inst)

#
# Measurements
#

rm.close()
```

But it does not bring the console to local mode. The only way so far is to turn it off and on again.

**Comment by clade** [comment]
With VISA, this should be available with the "control_ren" method. So you could try : 

<code>
power_meter._inst.control_ren(6)
</code>

Acording to the Thorlabs manual, you can set it abck to local by pressing the left or right key button.

**Comment by ilyaradko** [comment]
Wow, thank you very much! Switching to local by buttons does not work for some reason, but `control_ren()` method works perfectly. Thank you for the help.
