### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by mabl** [clade/ThorlabsPM100#9]
After #8 was merged, no release was made. It would be helpful to have that code released.

Thanks!

**Comment by clade** [comment]
Thanks for you comment. 
Version 1.2.2 is now released : https://github.com/clade/ThorlabsPM100/releases/tag/v1.2.2 and on [Pypi](https://files.pythonhosted.org/packages/0a/5e/ef1769d291e959d19bd8a5a488e899897ff1f657eca39fe8db872fa691dd/ThorlabsPM100-1.2.2.tar.gz)
